version: "3"
services:
  redis-master:
    image: redis:5.0.3
    ports:
      - "6379"
    labels:
      - redis
      - redis-master
    volumes:
      - "redis-master-data:/data"
  redis-slave:
    image: redis:5.0.3
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6379"
    links:
      - redis-master
    depends_on:
      - redis-master
    labels:
      - redis
      - redis-slave
    volumes:
      - "redis-slave-data:/data"
  redis-sentinel:
    build:
      context: ./sentinel
      args:
        - SENTINEL_QUORUM=2
        - SENTINEL_DOWN_THRESHOLD=7000
        - SENTINEL_FAILOVER_THRESHOLD=25000
    ports:
      - "26379"
    links:
      - redis-master
    depends_on:
      - redis-master
      - redis-slave
    labels:
      - redis
      - redis-sentinel
volumes:
  redis-master-data:
    driver: local
  redis-slave-data:
    driver: local